stages:
  - build

build_linux:
  stage: build
  script:
    - cargo build --release
    - cp target/release/gbemulator gbemulator_linux_amd64
    - strip gbemulator_linux_amd64
  artifacts:
    paths:
      - gbemulator_linux_amd64
  tags:
    - linux

build_windows:
  stage: build
  script:
    - vcpkg install sdl2:x64-windows
    - cargo build --release
    - mkdir gbemulator_windows_amd64
    - cp target/release/gbemulator.exe gbemulator_windows_amd64
    - cp ($env:VCPKG_HOME + "\installed\x64-windows\bin\SDL2.dll") gbemulator_windows_amd64
  artifacts:
    paths:
      - gbemulator_windows_amd64
  tags:
    - windows